name: Configuration Assistant
id: ConfigAssistant
key: ConfigAssistant
author_link: http://www.majordojo.com/
author_name: Byrne Reese
description: This plugin provides a simple YAML based framework for creating plugin and theme configuration options.
version: 1.8
static_version: 1
schema_version: 1

system_config_template: system_config.mtml

applications:
  cms:
    menus: $ConfigAssistant::ConfigAssistant::Theme::update_menus
    methods:
      theme_options:    $ConfigAssistant::ConfigAssistant::Plugin::theme_options
      ca_config_entry:  $ConfigAssistant::ConfigAssistant::Plugin::list_entry_mini
      ca_select_entry:  $ConfigAssistant::ConfigAssistant::Plugin::select_entry
      ca_save_config:   $ConfigAssistant::ConfigAssistant::Plugin::save_config
      paypal_donate:    $ConfigAssistant::ConfigAssistant::Plugin::paypal_donate
      edit_templates:   $ConfigAssistant::ConfigAssistant::Plugin::edit_templates
      unlink_templates: $ConfigAssistant::ConfigAssistant::Plugin::unlink_templates
      run_static_copy:  $ConfigAssistant::ConfigAssistant::Static::manual_run
      select_theme:     $ConfigAssistant::ConfigAssistant::Theme::select_theme
#      search_theme:     $ConfigAssistant::ConfigAssistant::Theme::search_theme
      setup_theme:      $ConfigAssistant::ConfigAssistant::Theme::setup_theme
    page_actions: $ConfigAssistant::ConfigAssistant::Theme::update_page_actions
    search_apis:
      entry:
        setup_terms_args: $ConfigAssistant::ConfigAssistant::Plugin::entry_search_api_prep

callbacks:
  MT::App::CMS::template_param.cfg_plugin: $ConfigAssistant::ConfigAssistant::Plugin::xfrm_cfg_plugin_param
  MT::App::CMS::template_source.cfg_plugin: $ConfigAssistant::ConfigAssistant::Plugin::xfrm_cfg_plugin
  MT::App::CMS::template_source.edit_template: $ConfigAssistant::ConfigAssistant::Theme::xfrm_disable_tmpl_link
  blog_template_set_change: $ConfigAssistant::ConfigAssistant::Theme::template_set_change
  

init_app: $ConfigAssistant::ConfigAssistant::Init::init_app

config_settings:
  PluginStaticVersion:
    type: 'HASH'

config_types:
  text: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_text
  file: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_file
  colorpicker: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_colorpicker
  textarea:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_textarea
  radio: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_radio
  select: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_select
  blogs: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_blogs
  checkbox: 
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_checkbox
  radio-image:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_radio_image
  entry:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_entry
  tagged-entry:
    handler: $ConfigAssistant::ConfigAssistant::Plugin::type_tagged_entry

upgrade_functions:
  static_copy:
    # A version_limit is required to trigger the upgrade function. So, just
    # use a way big one, just so I don't have to remember to update it.
    version_limit: 999
    handler: $ConfigAssistant::ConfigAssistant::Static::upgrade
    
object_types:
  theme: ConfigAssistant::Theme

skip_static:
  - .psd
